INSERT INTO books_dtls VALUES
(1, 'The Silent Forest', 'A. K. Sharma', 299),
(2, 'Code Beyond Limits', 'Neha Verma', 499),
(3, 'Mystery of Time', 'R. K. Singh', 350),
(4, 'Learning SQL Fast', 'Anita Desai', 450),
(5, 'Journey Within', 'S. R. Mehta', 275),
(6, 'Python Made Easy', 'Rohit Kulkarni', 520),
(7, 'The Last Kingdom', 'Vikas Malhotra', 399),
(8, 'Data Structures 101', 'Pooja Nair', 480),
(9, 'Echoes of the Past', 'Amit Chatterjee', 310),
(10, 'AI for Beginners', 'Kunal Joshi', 650),
(11, 'The Dark Horizon', 'Manoj Patil', 360),
(12, 'Web Development Basics', 'Sneha Kapoor', 430),
(13, 'Mind Over Matter', 'Dr. R. Iyer', 290),
(14, 'Cloud Computing Guide', 'Nitin Bansal', 575),
(15, 'Secrets of Success', 'Alok Mishra', 250),
(16, 'Java in Practice', 'Sunita Rao', 540),
(17, 'The Hidden Truth', 'Pankaj Gupta', 325),
(18, 'Operating Systems', 'K. V. Rao', 610),
(19, 'Winds of Change', 'Shilpa Kulkarni', 280),
(20, 'Cyber Security Essentials', 'Rahul Khanna', 699),
(21, 'The Art of Thinking', 'Meenal Shah', 340),
(22, 'Machine Learning Simplified', 'Arjun Kulkarni', 720),
(23, 'Lost in the City', 'Naveen Sood', 305),
(24, 'C Programming Handbook', 'Ramesh Kumar', 460),
(25, 'Rise of Empires', 'T. S. Menon', 390),
(26, 'DevOps Fundamentals', 'Harish Iyer', 580),
(27, 'Beyond the Stars', 'Priya Malhotra', 330),
(28, 'Database Design', 'Ankur Jain', 495),
(29, 'The Final Chapter', 'Sanjay Kulkarni', 370),
(30, 'Linux Administration', 'Deepak Yadav', 560),
(31, 'The Power of Habit', 'Kavita Joshi', 310),
(32, 'Big Data Analytics', 'Rohini Deshpande', 740),
(33, 'Shadows and Light', 'Ashwin Rao', 295),
(34, 'Software Testing Guide', 'Nisha Mehra', 420),
(35, 'Unspoken Words', 'Varun Desai', 285),
(36, 'Computer Networks', 'Mahesh Patankar', 610),
(37, 'The Golden Path', 'Ishita Sengupta', 355),
(38, 'Spring Boot in Action', 'Aditya Kulkarni', 590),
(39, 'Fragments of Life', 'Reema Arora', 270),
(40, 'Algorithms Explained', 'Saurabh Mishra', 680),
(41, 'The Long Road', 'Kiran Jadhav', 300),
(42, 'Microservices Architecture', 'Prateek Saxena', 750),
(43, 'Dreams and Reality', 'Anjali Kulkarni', 290),
(44, 'HTML & CSS Design', 'Vivek Pandey', 410),
(45, 'The Turning Point', 'Ritu Malhotra', 320),
(46, 'REST API Development', 'Aakash Verma', 530),
(47, 'Moments in Time', 'Shreya Banerjee', 305),
(48, 'Software Engineering', 'P. S. Gill', 640),
(49, 'Paths Untraveled', 'Nilesh Patil', 335),
(50, 'Full Stack Development', 'Mohit Agarwal', 780);
